In [1]:
# Deep Learning is the most exciting and powerful branch of Machine Learning. Deep Learning models can be used for a variety of complex tasks:

# Artificial Neural Networks for Regression and Classification
# Convolutional Neural Networks for Computer Vision
# Recurrent Neural Networks for Time Series Analysis
# Self Organizing Maps for Feature Extraction
# Deep Boltzmann Machines for Recommendation Systems
# Auto Encoders for Recommendation Systems

In [1]:
# Deep learning is a subset of machine learning that involves algorithms inspired by the structure and function of the brain,
# known as artificial neural networks. It is a key technology behind many advances in artificial intelligence (AI), 
# enabling computers to recognize patterns,
# make decisions, and learn from data in ways that were not possible before.
# Key Characteristics of Deep Learning
# Neural Networks: Deep learning models are based on neural networks, which are composed of layers of interconnected nodes (neurons).
# Each node processes input data and passes the result to the next layer.

# Depth of Layers: The "deep" in deep learning refers to the number of layers in the neural network.
# Deep learning models typically have multiple hidden layers between the input and output layers, allowing them to learn more complex patterns.

# Representation Learning: One of the strengths of deep learning is its ability to automatically extract and learn features from raw data,
# such as images, text, or audio, without the need for manual feature engineering.

# Large Scale Data and Computation: Deep learning models require large amounts of data and significant computational resources for training. 
# The rise of big data and advances in hardware (such as GPUs) have been crucial in making deep learning feasible and effective.
# Applications of Deep Learning
# Computer Vision: Object detection, image recognition, and medical image analysis.
# Natural Language Processing (NLP): Machine translation, sentiment analysis, and text generation.
# Speech Recognition: Transcribing spoken language into text.
# Autonomous Systems: Self-driving cars and robotics.
# Recommender Systems: Personalized recommendations for movies, products, or music.

In [ ]:
# Advantages of Deep Learning
# Automated Feature Extraction: Reduces the need for manual feature engineering.
# High Accuracy: Capable of achieving high accuracy in various tasks, sometimes surpassing human performance.
# Scalability: Can handle large and complex datasets.

In [ ]:
# Challenges of Deep Learning
# Data Requirement: Requires large datasets to perform effectively.
# Computational Cost: Demands significant computational power and resources.
# Interpretability: Deep learning models are often seen as black boxes, making it difficult to understand how they make decisions.
# Deep learning continues to be a rapidly evolving field, with ongoing research pushing the boundaries of what AI can achieve.

In [ ]:
# Artificial Neural Networks (ANNs) are a type of deep learning model inspired by the human brain.
# They consist of interconnected layers of nodes (neurons),
# each performing a simple computation. ANNs are used in various tasks such as classification, regression, and pattern recognition.


In [ ]:

# Artificial Neural Networks (ANNs) are computational models inspired by the human brain's neural networks.
# They consist of layers of interconnected nodes, or neurons, which process data in a way that mimics the way the human brain operates.
# ANNs are a fundamental concept in machine learning and deep learning, often used for tasks such as classification, regression, and pattern recognition.

# Key Components of an ANN
# Neurons: Basic units that receive input, process it, and pass the output to the next layer.
# Layers: ANNs typically consist of an input layer, one or more hidden layers, and an output layer.
# Weights and Biases: Parameters that are adjusted during training to minimize the error of predictions.
# Activation Functions: Functions that introduce non-linearity into the network, enabling it to learn complex patterns.
# Common activation functions include ReLU, sigmoid, and tanh.

In [ ]:
# Key Concepts
# Neuron: 
# The basic unit in a neural network. It receives inputs, processes them, and passes the output to the next layer.
(Dendrites:recieve input,axon:transmit info to other neurons)
# Activation Function:
# Introduces non-linearity into the network, enabling it to learn complex patterns. Common activation functions include ReLU (Rectified Linear Unit), sigmoid, and tanh.
# Weights and Biases:
# Parameters learned during training that affect the output of each neuron.
# Loss Function:
# Measures the difference between the predicted output and the actual output. The goal of training is to minimize the loss.
# Optimizer:
#  An aglorithm that adjusts weights and biases to minimize the loss. Common optimizers include SGD (Stochastic Gradient Descent), Adam, and RMSprop.

In [ ]:
# Basic Structure of an ANN
# Input Layer: Takes the input data.
# Hidden Layers: Intermediate layers that transform the input into something the output layer can use. 
# These layers can be deep, meaning they have many layers.
# Output Layer: Produces the final prediction or classification.

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.16.1'

In [9]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [10]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [11]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [7]:
print(y)

[1 0 1 ... 1 1 0]


In [12]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

In [13]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [17]:
X

array([[1.0, 0.0, 1.0, ..., 1, 1, 101348.88],
       [1.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 1.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 1.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 1.0, ..., 1, 0, 38190.78]], dtype=object)

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [21]:
# The line ann = tf.keras.models.Sequential() in Python, using TensorFlow's Keras API, 
# serves the purpose of initializing a sequential model for building artificial neural networks (ANNs).
ann = tf.keras.models.Sequential()

In [22]:
# The line ann.add(tf.keras.layers.Dense(units=6, activation='relu')) in TensorFlow/Keras is used 
# to add a dense (fully connected) layer to a sequential model (ann).
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [23]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [25]:
# The line ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) in TensorFlow/Keras is used to add the output layer to a sequential model (ann).
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [26]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 31s 31ms/step - accuracy: 0.2947 - loss: 0.7830
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 7s 26ms/step - accuracy: 0.7964 - loss: 0.6278
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 18ms/step - accuracy: 0.7925 - loss: 0.5870
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 9s 31ms/step - accuracy: 0.7954 - loss: 0.5568
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 9s 27ms/step - accuracy: 0.7984 - loss: 0.5337
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 8s 19ms/step - accuracy: 0.7889 - loss: 0.5233
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.8012 - loss: 0.4973
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.8000 - loss: 0.4836
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.7952 - loss: 0.4791
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7969 - loss: 0.4621
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.8010 - loss: 0.4524
Epoch 12/100
250/250 ━━━━━━━━